#!/usr/bin/env node
/**
 * Setup Wizard — openclaw-ws-proxy
 * Run: node setup.js
 *
 * Interactive CLI wizard to configure and test the ws-proxy for your setup.
 */

import { createInterface } from 'readline';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));
const logo = `
  ███╗   ███╗ █████╗ ██████╗ ███████╗
  ████╗ ████║██╔══██╗██╔══██╗██╔════╝
  ██╔████╔██║███████║██████╔╝███████╗
  ██║╚██╔╝██║██╔══██║██╔═══╝ ╚════██║
  ██║ ╚═╝ ██║██║  ██║██║     ███████║
  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚══════╝
  WS-PROXY SETUP WIZARD
`;

async function checkGateway() {
  console.log('\n🔍 Checking OpenClaw gateway...');
  try {
    const out = execSync('openclaw gateway status 2>&1', { encoding: 'utf8' });
    if (out.includes('RPC probe: ok')) {
      console.log('✅ Gateway is running');
      // Extract token from config
      try {
        const config = JSON.parse(fs.readFileSync(path.join(process.env.HOME || '/root', '.openclaw/openclaw.json'), 'utf8'));
        const token = config?.gateway?.token || config?.token;
        if (token) {
          console.log(`🔑 Gateway token found (${token.slice(0, 8)}...)`);
          return token;
        }
      } catch {}
      console.log('⚠️  Could not read token from config');
    } else {
      console.log('❌ Gateway not reachable:', out.slice(0, 200));
    }
  } catch (e) {
    console.log('❌ Could not run openclaw — is it installed?', e.message.slice(0, 100));
  }
  return null;
}

async function main() {
  console.log(logo);
  console.log('Welcome! This wizard will help you set up the ws-proxy.\n');

  // Step 1: Check gateway
  console.log('── Step 1: Gateway ──');
  const token = await checkGateway();

  // Step 2: Gateway URL
  console.log('\n── Step 2: Gateway WebSocket URL ──');
  const defaultWs = 'ws://127.0.0.1:45397';
  const gatewayWs = await ask(`Gateway WS URL [${defaultWs}]: `) || defaultWs;

  // Step 3: Port
  console.log('\n── Step 3: Proxy Port ──');
  const port = await ask('Proxy port [3002]: ') || '3002';

  // Step 4: MC type
  console.log('\n── Step 4: Mission Control ──');
  console.log('Which MC are you connecting?');
  console.log('  1. NERVE');
  console.log('  2. JARVIS Mission Control');
  console.log('  3. Autonomous AI Startup');
  console.log('  4. Other / Custom');
  const mcType = await ask('Choice [1]: ') || '1';

  const mcUrls = {
    '1': { name: 'NERVE', wsParam: 'ws://your-vps-ip:3002/ws?target=ws://127.0.0.1:45397' },
    '2': { name: 'JARVIS MC', wsParam: 'ws://your-vps-ip:3002/ws?target=ws://127.0.0.1:45397' },
    '3': { name: 'AI Startup', wsParam: 'ws://your-vps-ip:3002/ws?target=ws://127.0.0.1:45397' },
    '4': { name: 'Custom', wsParam: null },
  };
  const mc = mcUrls[mcType] || mcUrls['1'];

  let customWs = mc.wsParam;
  if (!mc.wsParam) {
    customWs = await ask('Custom WebSocket URL (use {{HOST}} for proxy host): ') || '';
  }

  // Step 5: Domain
  console.log('\n── Step 5: Domain (optional) ──');
  console.log('Do you have a domain for this? y/n');
  const hasDomain = (await ask(''))?.toLowerCase().startsWith('y');
  let domain = '';
  if (hasDomain) {
    domain = await ask('Domain (e.g. gateway.mydomain.com): ') || '';
  }

  // Step 6: Generate .env
  console.log('\n── Step 6: Environment File ──');
  const envContent = [
    '# openclaw-ws-proxy config',
    `GATEWAY_WS=${gatewayWs}`,
    `PORT=${port}`,
    token ? `# GATEWAY_TOKEN=${token}` : '# GATEWAY_TOKEN=your-token-here',
    '',
    '# Generated by setup.js',
    `MC_WS_URL=${customWs.replace('your-vps-ip', 'YOUR_VPS_IP')}`,
    domain ? `# DOMAIN=${domain}` : '',
  ].filter(l => l !== undefined).join('\n');

  fs.writeFileSync(path.join(__dirname, '.env'), envContent);
  console.log('✅ Written .env file');

  // Step 7: Docker compose
  console.log('\n── Step 7: Docker Compose ──');
  let compose = fs.readFileSync(path.join(__dirname, 'docker-compose.yml'), 'utf8');
  if (token) {
    compose = compose.replace('image:', `# GATEWAY_TOKEN=${token}\nimage:`);
  }
  fs.writeFileSync(path.join(__dirname, 'docker-compose.yml'), compose);
  console.log('✅ Updated docker-compose.yml');

  // Summary
  console.log('\n═══════════════════════════════════════');
  console.log('  SETUP COMPLETE');
  console.log('═══════════════════════════════════════\n');

  console.log('📦 To start the proxy:');
  console.log('   docker compose up -d\n');

  if (domain) {
    console.log(`🌐 Browser URL: wss://${domain}/ws?target=${gatewayWs}`);
  } else {
    console.log(`🌐 Browser URL: ws://YOUR_VPS_IP:${port}/ws?target=${gatewayWs}`);
  }

  console.log(`\n🔑 Gateway token: ${token ? `(${token.slice(0,8)}...)` : 'NOT FOUND — enter manually in .env'}`);

  console.log('\n📋 Next steps:');
  console.log('   1. Update YOUR_VPS_IP in the URL above');
  console.log('   2. Point your MC to the browser URL above');
  console.log('   3. docker compose up -d');
  console.log('   4. Visit /health to confirm proxy is running\n');

  rl.close();
}

main().catch(e => { console.error('Setup error:', e); rl.close(); process.exit(1); });
